// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzbkmmemesaamtnrcrgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6YmttbWVtZXNhYW10bnJjcmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NzU3ODIsImV4cCI6MjA5MDA1MTc4Mn0.5INt1erRXaX-L7IbmhDFq3g4LyrbFzdOr_Oqj7UDFYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});